void intakeMove(int speed, vex::percentUnits pt, vex::directionType Mdir);
void intakeMove(int speed, vex::velocityUnits vel, vex::directionType Mdir);
void intakeStop();
void outakeMove(int speed, vex::percentUnits pt, vex::directionType Mdir);
void outakeMove(int speed, vex::velocityUnits vel, vex::directionType Mdir);
void outakeStop();
void driveTrainControl(vex::directionType dir, int speed, vex::percentUnits pt);
void driveTrainControl(vex::turnType dir, int speed, vex::percentUnits pt);
void driveTrainControl(vex::directionType dir, int speed, vex::velocityUnits vel);
void driveTrainControl(vex::turnType dir, int speed, vex::velocityUnits vel);
void autoMain();
extern int dora;
extern int dora2;